=== amplience/dc-sample-blog-nextjs/schemas/blog.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://raw.githubusercontent.com/amplience/dc-sample-blog-nextjs/master/schemas/blog.json",
  "title": "Blog list",
  "description": "A list of blogs",
  "allOf": [
    {
      "$ref": "http://bigcontent.io/cms/schema/v1/core#/definitions/content"
    }
  ],
  "type": "object",
  "properties": {
    "title": {
      "title": "Title",
      "description": "Title of the blog",
      "type": "string",
      "minLength": 1,
      "maxLength": 100,
      "examples": ["Amplience Product Blog"]
    },
    "heading": {
      "title": "heading",
      "description": "Heading of the blog",
      "type": "string",
      "minLength": 1,
      "maxLength": 300,
      "examples": ["News & updates from the Amplience production development"]
    },
    "searchPlaceHolder": {
      "title": "Search Placeholder",
      "description": "Placeholder text for search box",
      "type": "string",
      "minLength": 0,
      "maxLength": 150,
      "examples": ["Search for articles and topics"]
    },
    "_meta":{
      "type":"object",
      "properties":{
        "deliveryKey":{
          "type":"string",
          "title":"Delivery key",
          "description": "The delivery key will be used to retrieve the blog when it is built",
          "examples": ["blog"]
        }
      },
      "required": ["deliveryKey"]
    }
  },
  "required": ["title", "heading", "searchPlaceHolder"],
  "propertyOrder": ["title", "heading", "searchPlaceHolder","_meta"]
}

=== amplience/dc-sample-blog-nextjs/components/visualization/__fixtures__/blog.json
{
  "_meta": {
    "schema": "https://raw.githubusercontent.com/amplience/dc-sample-blog-nextjs/master/schemas/blog.json",
    "deliveryId": "9cb44d61-d00b-49b7-b23b-72bb9a0a1de6",
    "deliveryKey": "blog",
    "name": "blog"
  },
  "title": "Blog",
  "heading": "heading",
  "searchPlaceHolder": "text"
}
